# Numpy
## Numpy - full form is Numerical python


In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.5'

In [13]:
result=0
for i in range(10):
    print(i)
    result +=i
print(result)

0
1
2
3
4
5
6
7
8
9
45


In [16]:
x=4
print(x)
x = 'four'
print(x)

4
four


In [17]:
# we can create a list
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
type(L[0])

int

In [23]:
# for string
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [25]:
# Fixed type array in Pyhton
import array
L = list(range(10))
A = array.array('i',L)
A

# we type i manually beacause it give idea that it is integer: 

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# creating arrays 
# Interger array
np.array([2,3,4,5])


array([2, 3, 4, 5])

In [31]:
# flout array
np.array([2.4,5,66,8])

array([ 2.4,  5. , 66. ,  8. ])

In [33]:
# we can explicitely define datatype 
np.array([2,4,5,4], dtype='float32')

array([2., 4., 5., 4.], dtype=float32)

In [34]:
# we can create nested list 
np.array([range(i,i+3) for i in [2,3,4]])

# It look like 2D array

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])