# Numpy
## Numpy - full form is Numerical python


In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.5'

In [13]:
result=0
for i in range(10):
    print(i)
    result +=i
print(result)

0
1
2
3
4
5
6
7
8
9
45


In [16]:
x=4
print(x)
x = 'four'
print(x)

4
four


In [17]:
# we can create a list
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
type(L[0])

int

In [23]:
# for string
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [25]:
# Fixed type array in Pyhton
import array
L = list(range(10))
A = array.array('i',L)
A

# we type i manually beacause it give idea that it is integer: 

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# creating arrays 
# Interger array
np.array([2,3,4,5])


array([2, 3, 4, 5])

In [31]:
# flout array
np.array([2.4,5,66,8])

array([ 2.4,  5. , 66. ,  8. ])

In [33]:
# we can explicitely define datatype 
np.array([2,4,5,4], dtype='float32')

array([2., 4., 5., 4.], dtype=float32)

In [34]:
# we can create nested list 
np.array([range(i,i+3) for i in [2,3,4]])

# It look like 2D array

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [41]:
# creating arrays from scrach 
np.zeros(10, dtype=int)
np.ones(10,dtype=float)
np.ones((3,5),dtype=float)
np.full((3,4),3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [44]:
np.arange(0,20,2)
# creating range , start from 0, end at 20, and step size 2 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
np.linspace(0,1,5)
# creating 5 values between 0 to 1 evenly spaced 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [47]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.32915938,  1.71670005, -1.32014345],
       [-0.42469676,  0.51733861, -0.17154353],
       [ 2.05421575, -0.53495147, -0.45901589]])

In [48]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.70461337, 0.89202042, 0.09472421],
       [0.79334798, 0.00999423, 0.1996688 ],
       [0.67343074, 0.67960328, 0.29253422]])

In [49]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[5, 6, 3],
       [3, 1, 6],
       [6, 9, 8]])

In [50]:
np.eye(3)
# identity matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
np.empty(3)

array([1., 1., 1.])

# KNN Example

In [59]:
X = rand.rand(10, 2)

NameError: name 'rand' is not defined